#!/bin/bash
set -euo pipefail

components=(
    smartthings
)

(cd homeassistant/components && git archive HEAD "${components[@]}") |
    ssh root@hass.lan.hails.org tar -C homeassistant/custom_components -xvf -
